import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })


import { ClerkProvider } from '@clerk/nextjs'
import LeftNavigation from './components/LeftNavigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>

        <div className='flex min-h-screen bg-black text-white/70'>
          <div>
            <LeftNavigation/>
          </div>
          <div className='flex-grow mb-0 '>
          {children}
          </div>
       
        </div>
        
        </body>
    </html>
    </ClerkProvider>
  )
}
